#include "TROOT.h"
#include "TFile.h"
#include "TTree.h"
#include "TBrowser.h"
#include "TH2.h"
#include "TH1F.h"
#include <iostream>
#include "time.h"

using namespace std;

TH1F* hG;

void tree1r()
{
   clock_t begin = clock();
   //read the Tree generated by tree1w and fill two histograms
   //note that we use "new" to create the TFile and TTree objects !
   //because we want to keep these objects alive when we leave this function.
   TFile *f = new TFile("tree.root");
   TTree *t1 = (TTree*)f->Get("t1");
   Float_t px, py, pz;
   Double_t random;
   Int_t ev;
   Float_t gaus;
//   t1->SetBranchAddress("px",&px);
//   t1->SetBranchAddress("py",&py);
//   t1->SetBranchAddress("pz",&pz);
//   t1->SetBranchAddress("random",&random);
//   t1->SetBranchAddress("ev",&ev);
   t1->SetBranchAddress("gaus",&gaus);

   //create two histograms
   hG   = new TH1F("hG","gaussian distribution",200,-10,10);

   //read all entries and fill the histograms
   Long64_t nentries = t1->GetEntries();
   for (Long64_t i=0;i<nentries;i++) {
     t1->GetEntry(i);
     hG->Fill(gaus);     
  }  
  
  clock_t end = clock();

  double time_spent = (double)(end - begin) / CLOCKS_PER_SEC;
  cout << "run time : " << time_spent << " s" <<  endl;

}

